[package]
name = "cti-view"
version = "0.0.1"
edition = "2024"

[dependencies]
anyhow = "1"
eframe = "0.32"
egui = "0.33"
rfd = "0.15"
zstd = "0.13"
lz4_flex = "0.11"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"